repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
        args: [ "--allow-missing-credentials" ]
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: no-commit-to-branch
        args: [ -b, main ]
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: check-datetime-now
        name: check_datetime_now
        description: Prefer datetime.utcnow()
        language: pygrep
        entry: 'datetime\.now\(\)'
        types: [ python ]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.4
    hooks:
      - id: python-safety-dependencies-check

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.1
    hooks:
      - id: hadolint
        args: [ "--ignore", "DL3008", "--ignore", "DL4006" , "--ignore", "DL3013" ]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        exclude: poetry.lock

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [ "--exclude=docs/*", "--ignore=E501,W503,E203" ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        additional_dependencies: [ "toml" ]
        args: [ --add-ignore=D1, -e ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: [ --py39-plus ]
