version: '3.1'

services:

  mongo:
    image: mongo:5.0.6
    restart: always
    environment:
      MONGO_INITDB_DATABASE: fastAppDB
    ports:
      - "27017:27017"
    volumes:
      - .mock/mongo.js:/docker-entrypoint-initdb.d/mongo.js
