[default]
TOKEN_ALGORITHM = 'HS256'
TOKEN_EXPIRE_MINUTES = 60
EMOJIS = ['🍏', '🍎', '🍐', '🍊', '🍋', '🍌', '🍉', '🍇', '🍓', '🫐', '🍈', '🍒', '🍑', '🥭', '🍍', '🥥', '🥝', '🍅']

[prod]
EMOJIS = ['⚽️', '🏀', '🏈', '⚾️', '🎾', '🏐', '🎱']
