[default]
TOKEN_ALGORITHM = 'HS256'
TOKEN_EXPIRE_MINUTES = 60
MONGODB_DATABASE = "fastAppDB"
MONGODB_CONFIG = { "user" = "fast-app-api", "password" = "123456", "host" = "127.0.0.1", "port" = "27017" }
EMOJIS = ['🍏', '🍎', '🍐', '🍊', '🍋', '🍌', '🍉', '🍇', '🍓', '🫐', '🍈', '🍒', '🍑', '🥭', '🍍', '🥥', '🥝', '🍅']

[prod]
EMOJIS = ['⚽️', '🏀', '🏈', '⚾️', '🎾', '🏐', '🎱']
